name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write # Ensure the workflow has write permissions to create tags and releases

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3 # Use the latest version of actions/checkout
        with:
          fetch-depth: 0 # Fetch full history to include tags

      # Step 2: Set up Git configuration for pushing tags
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # Set the remote URL with the Personal Access Token (PAT)
          git remote set-url origin https://x-access-token:${{ secrets.ORGANIZATION_REPO_TOKEN }}@github.com/SpectroCoin/WordPress-WooCommerce-Bitcoin-Payment-Gateway-Plugin.git
          # Authenticate with the token for Git push operations
          echo "https://x-access-token:${{ secrets.ORGANIZATION_REPO_TOKEN }}@github.com" > ~/.git-credentials
          git config --global credential.helper store

      # Step 3: Get PR Title or Manual Tag Input
      - name: Get PR Title or Manual Tag Input
        id: create_tag
        env: # Make sure the token is available in the environment
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_REPO_TOKEN }} # Use the same token to ensure it works
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # If manually triggered, use an input for the tag (or you can default to a specific tag)
            TAG_NAME="${{ github.event.inputs.tag_name }}"
          else
            # Get the pull request title if automatically triggered by PR merge
            TAG_NAME="${{ github.event.pull_request.title }}"
          fi

          echo "Using tag name: $TAG_NAME"

          # Create the tag
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"  # This push operation will now use the PAT token

          # Store the tag in the environment
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # Step 4: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_REPO_TOKEN }} # This uses the token for the GitHub API actions
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: |
            ${{ github.event.pull_request.body || 'Manual release' }}
          draft: false
          prerelease: false

      # Step 5: Create and upload spectrocoin.zip as a release asset
      - name: Create spectrocoin.zip
        run: |
          mkdir spectrocoin-accepting-bitcoin  # Create the folder inside the working directory
          # Copy only the necessary files and exclude the folder and unwanted files
          find . -maxdepth 1 ! -name 'spectrocoin-accepting-bitcoin' ! -name '.' ! -name '.git' ! -name '.github' ! -name 'README.txt' ! -name 'README.md' ! -name 'changelog.md' ! -name '.gitignore' -exec cp -r {} spectrocoin-accepting-bitcoin/ \;
          zip -r spectrocoin.zip spectrocoin-accepting-bitcoin  # Zip the folder

      - name: Upload spectrocoin.zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: $
