name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true # Only run if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch full history to include tags

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get the latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=TAG::$TAG"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG }} # Use the latest tag
          release_name: "Release for PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}" # Dynamic title from PR
          body: |
            ## Changelog
            PR Title: ${{ github.event.pull_request.title }}

            PR Description:
            ${{ github.event.pull_request.body }}

            ### Automatic Release for version ${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false
